# Build configuration for Cloudflare Pages
[build]
  # No build command needed for static site
  command = "echo 'Static site - no build required'"
  # Publish the root directory
  publish = "."
  
[build.environment]
  # Node.js version for any future build steps
  NODE_VERSION = "18"

# Page Rules for proper headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # PWA headers
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=3600"

# Functions configuration (for Cloudflare Pages Functions if needed)
[functions]
  directory = "functions"