name: Validate Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install conventional-commits validator
        run: go install github.com/cocogitto/cocogitto@latest

      - name: Validate commit messages
        run: |
          # Get the base branch (usually main or master)
          BASE_REF="${{ github.base_ref }}"
          
          # Get all commit messages since base branch
          git log --pretty=format:"%s" origin/$BASE_REF..HEAD | while read commit_msg; do
            echo "Validating: $commit_msg"
            
            # Check if commit follows conventional commit format
            if ! echo "$commit_msg" | grep -E '^(feat|fix|docs|style|refactor|perf|test|chore|ci|build)(\(.+\))?: .+'; then
              echo "❌ Commit message does not follow conventional commit format: $commit_msg"
              echo ""
              echo "Expected format: type(scope): description"
              echo "Types: feat, fix, docs, style, refactor, perf, test, chore, ci, build"
              echo ""
              echo "Examples:"
              echo "  feat: add new menu parsing feature"
              echo "  fix(api): handle empty menu responses"
              echo "  docs: update deployment instructions"
              echo "  chore: update dependencies"
              exit 1
            else
              echo "✅ Valid conventional commit: $commit_msg"
            fi
          done